### ISSUE TITLE
[DriveBackupV2] Failed to link your Google Drive account, please try again

### ISSUE THREAD

**Issue by FubarXS** [MaxMaeder/DriveBackupV2#107]
### Describe the bug

Hello, I was trying to install DriveBackupV2 on my server. But unfortunetly this error occured. 

Can you please help me?

### To Reproduce

Its just linking DriveBackupV2 with google drive.

### Screenshots / Videos

[08:45:09 WARN]: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
[08:45:09 WARN]: {
[08:45:09 WARN]:   "code" : 404,
[08:45:09 WARN]:   "errors" : [ {
[08:45:09 WARN]:     "domain" : "global",
[08:45:09 WARN]:     "location" : "file",
[08:45:09 WARN]:     "locationType" : "other",
[08:45:09 WARN]:     "message" : "File not found: ",
[08:45:09 WARN]:     "reason" : "notFound"
[08:45:09 WARN]:   } ],
[08:45:09 WARN]:   "message" : "File not found: "
[08:45:09 WARN]: }
[08:45:09 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
[08:45:09 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
[08:45:09 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
[08:45:09 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
[08:45:09 WARN]:        at DriveBackupV2.jar//com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1067)
[08:45:09 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
[08:45:09 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
[08:45:09 WARN]:        at DriveBackupV2.jar//com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
[08:45:09 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.uploaders.googledrive.GoogleDriveUploader.<init>(GoogleDriveUploader.java:84)
[08:45:09 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.uploaders.Authenticator$1.run(Authenticator.java:178)
[08:45:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[08:45:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[08:45:09 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[08:45:09 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[08:45:09 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[08:45:09 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[08:45:09 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[08:45:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[08:45:09 INFO]: [DriveBackupV2] Failed to link your Google Drive account, please try again
[08:45:09 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "this.drives" is null
[08:45:09 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.uploaders.googledrive.GoogleDriveUploader.setupSharedDrives(GoogleDriveUploader.java:287)
[08:45:09 WARN]:        at DriveBackupV2.jar//ratismal.drivebackup.uploaders.Authenticator$1.run(Authenticator.java:178)
[08:45:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[08:45:09 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[08:45:09 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1473)
[08:45:09 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[08:45:09 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[08:45:09 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[08:45:09 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[08:45:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### Server and Plugin Versions

![plugins](https://user-images.githubusercontent.com/118260582/201938149-b25e21df-97cd-4067-8f31-0b2c0e49d3e8.png)

**Comment by rhld16** [comment]
This bug has been fixed in the upcoming release
