### ISSUE TITLE
drivebackup linking account

### ISSUE THREAD

**Issue by FomkaWyverno** [MaxMaeder/DriveBackupV2#114]
### Describe the bug

[16:33:58] [Server thread/INFO] []: [DriveBackupV2] Failed to link your Google Drive account, please try again

[16:33:58] [Server thread/WARN] []: java.security.InvalidKeyException: Illegal key size or default parameters [16:33:58] [Server thread/WARN] []: at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026) [16:33:58] [Server thread/WARN] []: at javax.crypto.Cipher.implInit(Cipher.java:801) [16:33:58] [Server thread/WARN] []: at javax.crypto.Cipher.chooseProvider(Cipher.java:864) [16:33:58] [Server thread/WARN] []: at javax.crypto.Cipher.init(Cipher.java:1249) [16:33:58] [Server thread/WARN] []: at javax.crypto.Cipher.init(Cipher.java:1186) [16:33:58] [Server thread/WARN] []: at ratismal.drivebackup.uploaders.Obfusticate.decrypt(Obfusticate.java:37) [16:33:58] [Server thread/WARN] []: at ratismal.drivebackup.uploaders.Authenticator.authenticateUser(Authenticator.java:111) [16:33:58] [Server thread/WARN] []: at ratismal.drivebackup.handler.commandHandler.CommandHandler.onCommand(CommandHandler.java:83) [16:33:58] [Server thread/WARN] []: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [16:33:58] [Server thread/WARN] []: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153) [16:33:58] [Server thread/WARN] []: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689) [16:33:58] [Server thread/WARN] []: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:674) [16:33:58] [Server thread/WARN] []: at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:504) [16:33:58] [Server thread/WARN] []: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462) [16:33:58] [Server thread/WARN] []: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [16:33:58] [Server thread/WARN] []: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:673) [16:33:58] [Server thread/WARN] []: at java.lang.Thread.run(Unknown Source)

### To Reproduce

/drivebackup linkaccount googledrive

### Server and Plugin Versions

drivebackupv2 1.6.0
server core Magma 1.12.2 last version

**Comment by rhld16** [comment]
Which java version are you using?

**Comment by FomkaWyverno** [comment]
> Яку версію Java ви використовуєте?

8.

**Comment by rhld16** [comment]
Bug has been fixed with latest version
