### ISSUE TITLE
Drobox world folders failing to upload, but plugins folder succeeds

### ISSUE THREAD

**Issue by PutUsernameHere** [MaxMaeder/DriveBackupV2#128]
### Describe the bug

This issue seems different than #127, but I am unable to fully backup my server using Dropbox. The plugins folder is able to backed up, but all of the world folders fail. At first I thought it could be a file size issue but the overworld is the only slightly large one (~450MB zipped), while the nether and end are tiny (17MB and 1MB). Here's the relevant part of my log. All of the zip files are created, and given the amount of delay between uploads, they appear to go through some part of the process of uploading.

> issued server command: /drivebackup backup
[02:57:58 INFO]: [DriveBackupV2] Forcing a backup
[02:57:58 INFO]: [DriveBackupV2] Creating backups, the server may lag for a little while...
[02:57:58 INFO]: [DriveBackupV2] Doing backups for ".\world"
[02:58:18 INFO]: [DriveBackupV2] Uploading file to Dropbox
[03:01:34 INFO]: [DriveBackupV2] Failed to delete backups exceeding limit
[03:01:34 WARN]: ratismal.drivebackup.DriveBackup.lib.JSONException: JSONObject["entries"] not found.
[03:01:34 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.DriveBackup.lib.JSONObject.get(JSONObject.java:572)
[03:01:34 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.DriveBackup.lib.JSONObject.getJSONArray(JSONObject.java:765)
[03:01:34 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.uploaders.dropbox.DropboxUploader.getZipFiles(DropboxUploader.java:298)
[03:01:34 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.uploaders.dropbox.DropboxUploader.pruneBackups(DropboxUploader.java:250)
[03:01:34 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.uploaders.dropbox.DropboxUploader.uploadFile(DropboxUploader.java:219)
[03:01:34 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:379)
[03:01:34 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.UploadThread.run(UploadThread.java:238)
[03:01:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[03:01:34 INFO]: [DriveBackupV2] Failed to upload
[03:01:34 INFO]: [DriveBackupV2] Doing backups for ".\world_nether"
[03:01:35 INFO]: [DriveBackupV2] Uploading file to Dropbox
[03:01:41 INFO]: [DriveBackupV2] Failed to delete backups exceeding limit
[03:01:41 WARN]: ratismal.drivebackup.DriveBackup.lib.JSONException: JSONObject["entries"] not found.
[03:01:41 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.DriveBackup.lib.JSONObject.get(JSONObject.java:572)
[03:01:41 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.DriveBackup.lib.JSONObject.getJSONArray(JSONObject.java:765)
[03:01:41 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.uploaders.dropbox.DropboxUploader.getZipFiles(DropboxUploader.java:298)
[03:01:41 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.uploaders.dropbox.DropboxUploader.pruneBackups(DropboxUploader.java:250)
[03:01:41 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.uploaders.dropbox.DropboxUploader.uploadFile(DropboxUploader.java:219)
[03:01:41 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:379)
[03:01:41 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.UploadThread.run(UploadThread.java:238)
[03:01:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[03:01:41 INFO]: [DriveBackupV2] Failed to upload
[03:01:41 INFO]: [DriveBackupV2] Doing backups for ".\world_the_end"
[03:01:41 INFO]: [DriveBackupV2] Uploading file to Dropbox
[03:01:42 INFO]: [DriveBackupV2] Failed to delete backups exceeding limit
[03:01:42 WARN]: ratismal.drivebackup.DriveBackup.lib.JSONException: JSONObject["entries"] not found.
[03:01:42 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.DriveBackup.lib.JSONObject.get(JSONObject.java:572)
[03:01:42 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.DriveBackup.lib.JSONObject.getJSONArray(JSONObject.java:765)
[03:01:42 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.uploaders.dropbox.DropboxUploader.getZipFiles(DropboxUploader.java:298)
[03:01:42 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.uploaders.dropbox.DropboxUploader.pruneBackups(DropboxUploader.java:250)
[03:01:42 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.uploaders.dropbox.DropboxUploader.uploadFile(DropboxUploader.java:219)
[03:01:42 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:379)
[03:01:42 WARN]:        at DriveBackupV2+.jar//ratismal.drivebackup.UploadThread.run(UploadThread.java:238)
[03:01:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[03:01:42 INFO]: [DriveBackupV2] Failed to upload
[03:01:42 INFO]: [DriveBackupV2] Doing backups for "plugins"
[03:01:45 INFO]: [DriveBackupV2] Failed to include "plugins\LuckPerms\luckperms-h2-v2.mv.db" in the backup, is it locked? Do you have permission to access it?
[03:01:45 INFO]: [DriveBackupV2] Uploading file to Dropbox
[03:02:11 INFO]: [DriveBackupV2] Failed to upload
[03:02:11 INFO]: [DriveBackupV2] Failed to backup to Dropbox, verify all credentials are correct or diagnose the problem with /drivebackup test dropbox
[03:02:11 INFO]: [DriveBackupV2] Backup complete

### To Reproduce

1. Configure DriveBackup with default backup-list 
2. Enable dropbox backups
3. Manually call a backup
4. Observe only the plugins folder being in the dropbox folder

### Server and Plugin Versions

DriveBackupV2-1.6.1
Paper 1.20 build 17
Java 17
Windows 10

### Additional Context

If relevant, I have a Dropbox Professional 3TB plan

**Comment by PutUsernameHere** [comment]
Alright so I decided to test the issue again and it now is backing up with no issue. All that I've changed is update what version of Paper I am running ( git-Paper-47 (MC: 1.20.1) )
