### ISSUE TITLE
There was an issue attempting to check for the latest DriveBackupV2 release

### ISSUE THREAD

**Issue by DLmass** [MaxMaeder/DriveBackupV2#141]
### Describe the bug

```
[16:00:43 INFO]: [Backup] There was an issue attempting to check for the latest DriveBackupV2 release
[16:00:43 WARN]: java.lang.NumberFormatException
[16:00:43 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.plugin.updater.UpdateChecker.getLatest(UpdateChecker.java:103)
[16:00:43 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.plugin.updater.UpdateChecker$1.run(UpdateChecker.java:51)
[16:00:43 WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[16:00:43 WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:00:43 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:00:43 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:00:43 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:00:43 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

No idea what could be causing this. This error is being thrown upon restart.

### To Reproduce

No idea

### Server and Plugin Versions

1.20.2
DriveBackupV2-1.6.1

**Comment by lrmtheboss** [comment]
Does your server have access to api.curseforge.com?
It appears it does not, You may want to check with your hosting provider and see if they are blocking anything

**Comment by StillGreen-san** [comment]
We have the same issue on our server (Paper 1.20.4), but it does not happen all the time.
Looking back at the last two weeks it happened once or twice on the weekends and one time today. A different plugin also occasionally fails to check for updates. So there is a chance that, for us, its related to high network usage that results in a timeout for the request.

But more generally I'm wondering why the decision has been made to also print the stack trace if the update check fails? Seems a bit much to me, even if it is only marked as a warning.
