### ISSUE TITLE
Backup says it was uploaded successfully despite authorization error with Google Drive

### ISSUE THREAD

**Issue by RalphORama** [MaxMaeder/DriveBackupV2#15]
What the title says -- I changed my google password recently and forgot to re-auth DriveBackupV2, so I found this in my logs today:

```
[14:37:36 INFO]: [DriveBackupV2] Uploading file to Google Drive
[14:37:37 WARN]: com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
[14:37:37 WARN]: {
[14:37:37 WARN]:   "code" : 401,
[14:37:37 WARN]:   "errors" : [ {
[14:37:37 WARN]:     "domain" : "global",
[14:37:37 WARN]:     "location" : "Authorization",
[14:37:37 WARN]:     "locationType" : "header",
[14:37:37 WARN]:     "message" : "Invalid Credentials",
[14:37:37 WARN]:     "reason" : "authError"
[14:37:37 WARN]:   } ],
[14:37:37 WARN]:   "message" : "Invalid Credentials"
[14:37:37 WARN]: }
[14:37:37 WARN]:        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
[14:37:37 WARN]:        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
[14:37:37 WARN]:        at ratismal.drivebackup.googledrive.GoogleDriveUploader.getFolder(GoogleDriveUploader.java:418)
[14:37:37 WARN]:        at ratismal.drivebackup.googledrive.GoogleDriveUploader.createFolder(GoogleDriveUploader.java:371)
[14:37:37 WARN]:        at ratismal.drivebackup.googledrive.GoogleDriveUploader.uploadFile(GoogleDriveUploader.java:299)
[14:37:37 WARN]:        at ratismal.drivebackup.UploadThread.run(UploadThread.java:220)
[14:37:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[14:37:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[14:37:37 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:37:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:37:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:37:37 WARN]:        at java.lang.Thread.run(Thread.java:748)
[14:37:37 WARN]: com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
[14:37:37 WARN]:        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
[14:37:37 WARN]:        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
[14:37:37 WARN]:        at ratismal.drivebackup.googledrive.GoogleDriveUploader.createFolder(GoogleDriveUploader.java:380)
[14:37:37 WARN]:        at ratismal.drivebackup.googledrive.GoogleDriveUploader.uploadFile(GoogleDriveUploader.java:299)
[14:37:37 WARN]:        at ratismal.drivebackup.UploadThread.run(UploadThread.java:220)
[14:37:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[14:37:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[14:37:37 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:37:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:37:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:37:37 WARN]:        at java.lang.Thread.run(Thread.java:748)
[14:37:37 WARN]: com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
[14:37:37 WARN]:        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
[14:37:37 WARN]:        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1056)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
[14:37:37 WARN]:        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
[14:37:37 WARN]:        at ratismal.drivebackup.googledrive.GoogleDriveUploader.createFolder(GoogleDriveUploader.java:380)
[14:37:37 WARN]:        at ratismal.drivebackup.googledrive.GoogleDriveUploader.uploadFile(GoogleDriveUploader.java:299)
[14:37:37 WARN]:        at ratismal.drivebackup.UploadThread.run(UploadThread.java:220)
[14:37:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[14:37:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[14:37:37 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:37:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:37:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:37:37 WARN]:        at java.lang.Thread.run(Thread.java:748)
[14:37:37 INFO]: [DriveBackupV2] File uploaded in 0.19 seconds (26373.68KB/s)
[14:37:37 INFO]: [DriveBackupV2] There are 1 file(s) which exceeds the local limit of 0, deleting oldest
[14:37:37 INFO]: [DriveBackupV2] Backup complete, the next backup is at 9:30 AM Wed, Oct 7
```

**Comment by MaxMaeder** [comment]
This must be an issue with the Google Drive Java SDK, the plugin gets the upload status from this SDK.
