### ISSUE TITLE
[Bug] Regression, Plugin no longer loads when config is set up to use Nextcloud

### ISSUE THREAD

**Issue by whipped-cream** [MaxMaeder/DriveBackupV2#174]
### Describe the bug

When running the latest version of the plugin and the config is set up for Nextcloud backups the plugin doesn't load and fails with the following message 

```
mc_1  | [21:16:54] [Server thread/ERROR]: Error occurred while enabling DriveBackupV2 v1.6.3 (Is it up to date?)
mc_1  | java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.Map.get(Object)" is null
mc_1  | 	at DriveBackupV2.jar/ratismal.drivebackup.config.configSections.BackupList.parse(BackupList.java:126) ~[?:?]
mc_1  | 	at DriveBackupV2.jar/ratismal.drivebackup.config.ConfigParser.reload(ConfigParser.java:90) ~[?:?]
mc_1  | 	at DriveBackupV2.jar/ratismal.drivebackup.plugin.DriveBackup.onEnable(DriveBackup.java:77) ~[?:?]
mc_1  | 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
mc_1  | 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-45-4d20922]
mc_1  | 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-45-4d20922]
mc_1  | 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
mc_1  | 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-45-4d20922]
mc_1  | 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-45-4d20922]
mc_1  | 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752) ~[paper-1.21.jar:1.21-45-4d20922]
mc_1  | 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:514) ~[paper-1.21.jar:1.21-45-4d20922]
mc_1  | 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-45-4d20922]
mc_1  | 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[paper-1.21.jar:1.21-45-4d20922]
mc_1  | 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-45-4d20922]
mc_1  | 	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
mc_1  | [21:16:54] [Server thread/INFO]: Disabling DriveBackupV2 v1.6.3
```

This happens with 1.6.2 onwards.

When running from a blank config file the plugin loads and presumably works. The behavior is the same when running on 1.20.

Downgrading to 1.6.1 makes the plugin work as expected. 

### To Reproduce

1. Put DriveBackupV2.jar in plugins folder
2. Configure the config.yml to backup to nextcloud
3. Start the server

### Server and Plugin Versions

- Server software: Paper
- Server version: 1.21/1.20
- Plugin version: 1.6.2 onwards

### Logs

https://mclo.gs/ue3jrwA

### Config

https://pastebin.com/rsic69wH

### Additional Information

Please ignore the rest of the errors in the logs. I'm working on it

**Comment by lrmtheboss** [comment]
You can use the latest dev build until the next release.
