### ISSUE TITLE
NullPointerException when running backup

### ISSUE THREAD

**Issue by isteiger** [MaxMaeder/DriveBackupV2#33]
I installed some Vanilla Tweaks datapacks, and it stopped backing up and gave me the below errors:

`
java.lang.NullPointerException
at ratismal.drivebackup.util.FileUtil.generateFileList(FileUtil.java:246)
at ratismal.drivebackup.util.FileUtil.generateFileList(FileUtil.java:247)
at ratismal.drivebackup.util.FileUtil.generateFileList(FileUtil.java:247)
at ratismal.drivebackup.util.FileUtil.generateFileList(FileUtil.java:213)
at ratismal.drivebackup.util.FileUtil.makeBackup(FileUtil.java:106)
at ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:270)
at ratismal.drivebackup.UploadThread.run(UploadThread.java:196)
at java.base/java.lang.Thread.run(Unknown Source)
`

Removing the datapacks seems to have fixed the issue. The datapacks have spaces in their names, so this may be the cause.

**Comment by rhld16** [comment]
I am not able to reproduce this issue. Are you able to provide more details?

**Comment by rhld16** [comment]
This issue has been stale for over 3 months now so I'll have to close it but if you experience it again please open another issue.
