### ISSUE TITLE
MySQL backup errors

### ISSUE THREAD

**Issue by prefislt** [MaxMaeder/DriveBackupV2#59]
Getting error spam when making MySQL database backup. End result is almost empty database with many NULL tables. 

```
>.... [16:14:43 INFO]: [DriveBackupV2] Downloading databases from a MySQL server (***.***.***.**-3306) to include in backup
>.... [16:14:43 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.last(ResultSetImpl.java:1729)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getDataInsertStatement(MySQLUploader.java:161)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getInsertStatements(MySQLUploader.java:284)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:86)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:69)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.makeExternalDatabaseBackup(UploadThread.java:442)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.run(UploadThread.java:158)
>.... [16:14:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [16:14:43 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.last(ResultSetImpl.java:1729)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getDataInsertStatement(MySQLUploader.java:161)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getInsertStatements(MySQLUploader.java:284)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:86)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:69)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.makeExternalDatabaseBackup(UploadThread.java:442)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.run(UploadThread.java:158)
>.... [16:14:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [16:14:43 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.last(ResultSetImpl.java:1729)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getDataInsertStatement(MySQLUploader.java:161)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getInsertStatements(MySQLUploader.java:284)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:86)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:69)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.makeExternalDatabaseBackup(UploadThread.java:442)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.run(UploadThread.java:158)
>.... [16:14:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [16:14:43 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.last(ResultSetImpl.java:1729)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getDataInsertStatement(MySQLUploader.java:161)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getInsertStatements(MySQLUploader.java:284)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:86)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:69)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.makeExternalDatabaseBackup(UploadThread.java:442)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.run(UploadThread.java:158)
>.... [16:14:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [16:14:43 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.last(ResultSetImpl.java:1729)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getDataInsertStatement(MySQLUploader.java:161)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getInsertStatements(MySQLUploader.java:284)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:86)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:69)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.makeExternalDatabaseBackup(UploadThread.java:442)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.run(UploadThread.java:158)
>.... [16:14:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [16:14:43 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.last(ResultSetImpl.java:1729)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getDataInsertStatement(MySQLUploader.java:161)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getInsertStatements(MySQLUploader.java:284)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:86)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:69)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.makeExternalDatabaseBackup(UploadThread.java:442)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.run(UploadThread.java:158)
>.... [16:14:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [16:14:43 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.last(ResultSetImpl.java:1729)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getDataInsertStatement(MySQLUploader.java:161)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getInsertStatements(MySQLUploader.java:284)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:86)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:69)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.makeExternalDatabaseBackup(UploadThread.java:442)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.run(UploadThread.java:158)
>.... [16:14:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:831)
>.... [16:14:43 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
>.... [16:14:43 WARN]: at com.mysql.cj.jdbc.result.ResultSetImpl.last(ResultSetImpl.java:1729)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getDataInsertStatement(MySQLUploader.java:161)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.getInsertStatements(MySQLUploader.java:284)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:86)
>.... [16:14:43 WARN]: at ratismal.drivebackup.mysql.MySQLUploader.downloadDatabase(MySQLUploader.java:69)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.makeExternalDatabaseBackup(UploadThread.java:442)
>.... [16:14:43 WARN]: at ratismal.drivebackup.UploadThread.run(UploadThread.java:158)
>.... [16:14:43 WARN]: at java.base/java.lang.Thread.run(Thread.java:831) 
```
Full error log: [https://mclo.gs/HAPBDKW](https://mclo.gs/HAPBDKW)

Config:
```
external-backup-list:
- hostname: "***.***.***.**"
  port: 3306
  username: "*****"
  password: "***************"
  format: "'Backup-mysql-database-'yyyy-M-d--HH-mm'.zip'"
  type: "mysqlDatabase"
  ssl: false
  databases:
  - name: "****_***"
 ```
  
Plugin version: **1.4.0**
Java version: **16.0.1**
Server software: **AirplanePurpur**
Server software version: **git-AirplanePurpur-22 (MC: 1.17.1)**

**Comment by rhld16** [comment]
This issue is known and has been fixed for our upcoming update. If you want, join our discord and I could give you a custom 1.4.0 build which has this issue fixed
