### ISSUE TITLE
Do not delete old backups on onedrive

### ISSUE THREAD

**Issue by thiagogebrimm** [MaxMaeder/DriveBackupV2#74]
### Describe the bug

Do not delete old backups on onedrive

### To Reproduce

Just leave the backup running on onedrive, at the end it gives the error

### Screenshots / Videos

```
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/INFO]: [DriveBackup] Failed to delete backups exceeding limit
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: ratismal.drivebackup.DriveBackup.lib.JSONException: JSONObject["value"] not found.
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.JSONObject.get(JSONObject.java:572)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.JSONObject.getJSONArray(JSONObject.java:765)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.uploaders.onedrive.OneDriveUploader.pruneBackups(OneDriveUploader.java:448)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.uploaders.onedrive.OneDriveUploader.uploadFile(OneDriveUploader.java:233)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:367)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.run(UploadThread.java:231)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/INFO]: [DriveBackup] Failed to upload
[04:05:33] [Craft Scheduler Thread - 9453 - DriveBackupV2/INFO]: [DriveBackup] There are 1 file(s) which exceeds the local limit of 0, deleting oldest
[04:05:34] [Craft Scheduler Thread - 9453 - DriveBackupV2/INFO]: [DriveBackup] Failed to backup to OneDrive, verify all credentials are correct or diagnose the problem with /drivebackup test onedrive
[04:05:34] [Craft Scheduler Thread - 9453 - DriveBackupV2/INFO]: [DriveBackup] Backup complete
[04:05:34] [Craft Scheduler Thread - 9453 - DriveBackupV2/INFO]: [DriveBackup] The next backup is at 3:00 AM Thu, Nov 4 GMT-3
```

### Server and Plugin Versions

Server version: Purpur 1423 build
Plugin version: 1.5.3

**Comment by rhld16** [comment]
What's the result of `/drivebackup test onedrive`?

**Comment by thiagogebrimm** [comment]
![image](https://user-images.githubusercontent.com/75040244/140415497-07af5429-1c7c-4fb8-a754-e5a852e72678.png)

**Comment by rhld16** [comment]
Ok thanks, could you join our discord so I can give you a debug build so we can try to figure out what's wrong?

**Comment by rhld16** [comment]
Fixed as of latest version (confirmed with reporter)
