### ISSUE TITLE
FTP Connection Not Open Error

### ISSUE THREAD

**Issue by JLLeitschuh** [MaxMaeder/DriveBackupV2#82]
### Describe the bug

I've applied the plugin, and I'm using the FTP configuration. I'm getting the following error:

```
[20:25:17 WARN]: java.io.IOException: Connection is not open
[20:25:17 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:505)
[20:25:17 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:635)
[20:25:17 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.cwd(FTP.java:867)
[20:25:17 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTPClient.changeWorkingDirectory(FTPClient.java:1317)
[20:25:17 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.uploaders.ftp.FTPUploader.resetWorkingDirectory(FTPUploader.java:386)
[20:25:17 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.uploaders.ftp.FTPUploader.uploadFile(FTPUploader.java:208)
[20:25:17 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:371)
[20:25:17 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.run(UploadThread.java:235)
[20:25:17 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:25:17 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:25:17 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:25:17 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:25:17 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:25:17 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:25:17 INFO]: §6[§4DriveBackupV2§6] §3Failed to upload
[20:25:17 INFO]: §6[§4DriveBackupV2§6] §3There are 1 file(s) which exceeds the local limit of 0, deleting oldest
[20:25:17 INFO]: §6[§4DriveBackupV2§6] §3Doing backups for ".\world_the_end"
[20:25:18 INFO]: §6[§4DriveBackupV2§6] §3Uploading file to (S)FTP
[20:25:18 WARN]: java.io.IOException: Connection is not open
[20:25:18 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:505)
[20:25:18 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:635)
[20:25:18 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.cwd(FTP.java:867)
[20:25:18 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTPClient.changeWorkingDirectory(FTPClient.java:1317)
[20:25:18 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.uploaders.ftp.FTPUploader.resetWorkingDirectory(FTPUploader.java:386)
[20:25:18 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.uploaders.ftp.FTPUploader.uploadFile(FTPUploader.java:208)
[20:25:18 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:371)
[20:25:18 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.run(UploadThread.java:235)
[20:25:18 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:25:18 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:25:18 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:25:18 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:25:18 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:25:18 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:25:18 INFO]: §6[§4DriveBackupV2§6] §3Failed to upload
[20:25:18 INFO]: §6[§4DriveBackupV2§6] §3There are 1 file(s) which exceeds the local limit of 0, deleting oldest
[20:25:18 INFO]: §6[§4DriveBackupV2§6] §3Doing backups for "plugins"
[20:25:19 INFO]: §6[§4DriveBackupV2§6] §3Uploading file to (S)FTP
[20:25:19 WARN]: java.io.IOException: Connection is not open
[20:25:19 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:505)
[20:25:19 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.sendCommand(FTP.java:635)
[20:25:19 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTP.cwd(FTP.java:867)
[20:25:19 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.DriveBackup.lib.net.ftp.FTPClient.changeWorkingDirectory(FTPClient.java:1317)
[20:25:19 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.uploaders.ftp.FTPUploader.resetWorkingDirectory(FTPUploader.java:386)
[20:25:19 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.uploaders.ftp.FTPUploader.uploadFile(FTPUploader.java:208)
[20:25:19 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.doSingleBackup(UploadThread.java:371)
[20:25:19 WARN]: 	at DriveBackupV2.jar//ratismal.drivebackup.UploadThread.run(UploadThread.java:235)
[20:25:19 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:25:19 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:25:19 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:25:19 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:25:19 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:25:19 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

I'm running with the following config file:

```
#################################################
# DriveBackupV2   -   by Max Maeder (MaxTheGinus)
#################################################

# DOCUMENTATION HAS MOVED
# Now available online at: https://github.com/MaxMaeder/DriveBackupV2/wiki

version: 2

delay: 60
backup-thread-priority: 1
keep-count: 20
local-keep-count: 0
zip-compression: 1
backups-require-players: true
disable-saving-during-backups: true

scheduled-backups: true
backup-schedule-list:

backup-list:
- glob: "world*"
  format: "Backup-world-%FORMAT.zip"
  create: true
- path: "plugins"
  format: "Backup-plugins-%FORMAT.zip"
  create: true

external-backup-list:

local-save-directory: "backups"
remote-save-directory: "Minecraft_Server_Backups/ServerV2"

googledrive:
  enabled: false
  shared-drive-id: ""
onedrive:
  enabled: false
dropbox:
  enabled: false
webdav:
  enabled: false
  hostname: "http://example.com/directory"
  username: "Username"
  password: "Password"
ftp:
  enabled: true
  hostname: "10.50.6.139"
  port: 21
  sftp: false
  ftps: false
  username: "JLLeitschuh_Minecraft_FTP"
  password: "redacted"
  sftp-public-key: 
  sftp-passphrase: 
  working-dir:

messages:
  send-in-chat: true
  prefix: "&6[&4DriveBackupV2&6] "
  default-color: "&3"

advanced:
  metrics: true
  update-check: true
  suppress-errors: false
  debug: false
  date-language: "en"
  date-timezone: "-00:00"
  ftp-file-separator: "/"
  ```

### To Reproduce

Specify the config file above & launch the server. Attempting to run the backup will result in the errors above.

### Server and Plugin Versions

`DriveBackupV2 v1.5.4`
Sever: `This server is running Paper version git-Paper-133 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5e30e19)`

The server is running under windows 10. 

### Additional Context

The FTP server is running on a Synology NAS Model DS920_ with version DSM 7.0.1-42218 of the software

I noticed that the `backups` file was created correctly under the server's root directory, however the `plugins`, `world`, `world_nether` and `world_the_end` directories all seem to be empty.

Running the `drivebackup test ftp` command results in the following:

```
[21:41:31 INFO]: ElberonShadow issued server command: /drivebackup test ftp
[21:41:31 INFO]: §6[§4DriveBackupV2§6] §3Beginning the test on (S)FTP
[21:41:36 INFO]: §6[§4DriveBackupV2§6] §3The (S)FTP test was successful
```

**Comment by rhld16** [comment]
We are aware of this issue but due to the minority usage of FTP and a lack of free time we have not yet released the bugfix. Could you try the latest build from the Actions tab?

**Comment by JLLeitschuh** [comment]
I ended up using a different plugin. 

No worries at all! Regardless, thanks for creating this plugin!

**Comment by rhld16** [comment]
No worries! If you don't mind me asking; was this bug the main reason for changing plugin or could we do something better?

**Comment by JLLeitschuh** [comment]
Hi @rhld16,

I needed a plugin with FTP support. I wanted to upload backup to my NAS server, so yes this was the primary reason that I didn't end up using this plugin. I ended up using [eBackup](https://www.spigotmc.org/resources/ebackup-simple-and-reliable-backups-for-your-server-supports-ftp-sftp.69917/)

Again, I come into interactions with OSS without many expectations. I get that the maintainers of these projects are unpaid and are doing this for fun in their free time. I have no expectations, but I do really appreciate the hard work that OSS maintainers and plugin authors put into making our lives so much easier.

So even though I didn't end up using this plugin, thank you for developing it! 😄

**Comment by rhld16** [comment]
❤️
