### ISSUE TITLE
Error enabling drive backup

### ISSUE THREAD

**Issue by TsunayoshiSawada** [MaxMaeder/DriveBackupV2#89]
### Describe the bug

[11:28:18 INFO]: [DriveBackupV2] Enabling DriveBackupV2 v1.5.4
[11:28:20 INFO]: [DriveBackupV2] Automatically migrating config to version 2
[11:28:20 ERROR]: Error occurred while enabling DriveBackupV2 v1.5.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
        at ratismal.drivebackup.config.ConfigMigrator.migrate(ConfigMigrator.java:55) ~[DriveBackupV2.jar:?]
        at ratismal.drivebackup.plugin.DriveBackup.onEnable(DriveBackup.java:75) ~[DriveBackupV2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-160]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-160]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-160]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-160]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-160]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-160]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-160]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Started the server is all 

### Server and Plugin Versions

The plugin is at 1.5.4
Server is at 1.18.1

### Additional Context

Note that i raised an issue earlier too at 
https://github.com/MaxMaeder/DriveBackupV2/issues/85

It was closed saying that it was fixed in a bug fix but I don't see a new release, so idk how that bug fix helps me, further more another query asked on it got ignored, so I'm still just as lost.

**Comment by TsunayoshiSawada** [comment]
Thank you, I was just lost on where do I get the new jar. Just downloaded it and will begin testing now.

**Comment by TsunayoshiSawada** [comment]
![image](https://user-images.githubusercontent.com/34431649/155886943-d4c4e767-6dda-41a7-a8d7-0e56f711f26a.png)
Works
